# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calculator.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(90, 40, 71, 41))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(90, 100, 71, 16))
        self.label_2.setObjectName("label_2")
        self.Addition = QtWidgets.QPushButton(self.centralwidget)
        self.Addition.setGeometry(QtCore.QRect(100, 160, 151, 71))
        self.Addition.setObjectName("Addition")
        self.Subtraction = QtWidgets.QPushButton(self.centralwidget)
        self.Subtraction.setGeometry(QtCore.QRect(260, 160, 151, 71))
        self.Subtraction.setObjectName("Subtraction")
        self.Multiplication = QtWidgets.QPushButton(self.centralwidget)
        self.Multiplication.setGeometry(QtCore.QRect(420, 160, 151, 71))
        self.Multiplication.setObjectName("Multiplication")
        self.Division = QtWidgets.QPushButton(self.centralwidget)
        self.Division.setGeometry(QtCore.QRect(260, 240, 151, 71))
        self.Division.setObjectName("Division")
        self.lbl_Result = QtWidgets.QLabel(self.centralwidget)
        self.lbl_Result.setGeometry(QtCore.QRect(160, 320, 311, 171))
        self.lbl_Result.setObjectName("lbl_Result")
        self.Number_1 = QtWidgets.QLineEdit(self.centralwidget)
        self.Number_1.setGeometry(QtCore.QRect(180, 30, 351, 51))
        self.Number_1.setObjectName("Number_1")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(180, 90, 351, 51))
        self.lineEdit_2.setObjectName("lineEdit_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Number 1: "))
        self.label_2.setText(_translate("MainWindow", "Number 2:"))
        self.Addition.setText(_translate("MainWindow", "Addition"))
        self.Subtraction.setText(_translate("MainWindow", "Subtraction"))
        self.Multiplication.setText(_translate("MainWindow", "Multiplication"))
        self.Division.setText(_translate("MainWindow", "Division"))
        self.lbl_Result.setText(_translate("MainWindow", "Result: "))
