# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Texteditor.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Workspace = QtWidgets.QTextEdit(self.centralwidget)
        self.Workspace.setGeometry(QtCore.QRect(20, 50, 751, 401))
        self.Workspace.setAutoFillBackground(False)
        self.Workspace.setObjectName("Workspace")
        self.Save_file = QtWidgets.QPushButton(self.centralwidget)
        self.Save_file.setGeometry(QtCore.QRect(20, 460, 181, 61))
        self.Save_file.setObjectName("Save_file")
        self.Open_file = QtWidgets.QPushButton(self.centralwidget)
        self.Open_file.setGeometry(QtCore.QRect(210, 460, 181, 61))
        self.Open_file.setObjectName("Open_file")
        self.Undo = QtWidgets.QPushButton(self.centralwidget)
        self.Undo.setGeometry(QtCore.QRect(400, 460, 181, 61))
        self.Undo.setObjectName("Undo")
        self.Redo = QtWidgets.QPushButton(self.centralwidget)
        self.Redo.setGeometry(QtCore.QRect(590, 460, 181, 61))
        self.Redo.setObjectName("Redo")
        self.File_Name = QtWidgets.QLineEdit(self.centralwidget)
        self.File_Name.setGeometry(QtCore.QRect(110, 10, 661, 31))
        self.File_Name.setObjectName("File_Name")
        self.filename_lbl = QtWidgets.QLabel(self.centralwidget)
        self.filename_lbl.setGeometry(QtCore.QRect(30, 10, 81, 31))
        self.filename_lbl.setObjectName("filename_lbl")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Save_file.setText(_translate("MainWindow", "Save File"))
        self.Open_file.setText(_translate("MainWindow", "Open File"))
        self.Undo.setText(_translate("MainWindow", "Undo"))
        self.Redo.setText(_translate("MainWindow", "Redo"))
        self.filename_lbl.setText(_translate("MainWindow", "File Name: "))
